language: python

python:
    - "2.7"

virtualenv:
    system_site_packages: true

before_install:
  - python --version
  - sudo mkdir /etc/slurm-llnl
  - sudo cp slurm.conf /etc/slurm-llnl
#  - cp batchtools.conf.R tests/testthat
#  - sudo /etc/init.d/slurmctld restart
#  - sudo /etc/init.d/slurmd restart
  - sudo apt-get install -y slurm-llnl
  - sudo pip install requests
#  - sudo /usr/sbin/create-munge-key
  - sudo service munge start
  - cd jbrowse

script:
  - python tests/cluster_tests/clusterTest.py

branches:
    only:
        test-branch

notifications:
  email:
    recipients:
        - jcj52@nau.edu
    on_success: always
    on_failure: always
  # slack: capstoneteam2019-2020:99sHd15zMUNsTJEWiIUvlrF3
