language: python

python:
    - "3.5"

virtualenv:
    system_site_packages: true

before_install:
  - python --version
  - sudo mkdir /etc/slurm-llnl
  - sudo cp slurm.conf /etc/slurm-llnl
#  - cp batchtools.conf.R tests/testthat
#  - sudo /etc/init.d/slurmctld restart
#  - sudo /etc/init.d/slurmd restart
  - sudo apt-get install -y slurm-llnl
#  - sudo /usr/sbin/create-munge-key
  - sudo service munge start
  - cd jbrowse
  - pip install -r requirements.txt
```
env:
    global:
        - MOZ_HEADLESS=1
    addons:
        firefox: latest
```
before_script:
    - sleep 3
    - ./ourServer.py
    - sleep 3

script:
  - python tests/cluster_tests/clusterTest.py
  - python testing.py

branches:
    only:
        test-branch

notifications:
  slack: capstoneteam2019-2020:99sHd15zMUNsTJEWiIUvlrF3
