# see https://github.com/tdhock/PeakSegPipeline/blob/master/.travis.yml

language: python
python:
  - "2.7"

before_install:
  - sudo mkdir /etc/slurm-llnl
  - sudo cp slurm.conf /etc/slurm-llnl
  - cp batchtools.conf.R tests/testthat
  - sudo apt-get install -y slurm-llnl
  - sudo /usr/sbin/create-munge-key
  - sudo service munge start

script:  echo "Hello world"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  slack: capstoneteam2019-2020:bvR3ofKEeSgoYiI9E4pchZs6